### ISSUE TITLE
Gitleaks - Authentication error

### ISSUE THREAD

**Issue by cisel-dev** [cisel-dev/nightwatch#4]
Accès avec login et passwd ne fonctionne pas via l'l'outil Gitleaks
L'outil prend uniquement ce qu'il y a après le @ et il n'a donc pas l'information du compte utilisateur en entier

**Comment by cisel-dev** [comment]
Accès avec login et passwd ne fonctionne pas via l'l'outil Gitleaks
L'outil prend uniquement ce qu'il y a après le @ et il n'a donc pas l'information du compte utilisateur en entier

**Comment by badoqu** [comment]
Solved, problem of url encoding.
